spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: getaway
    password: getaway

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: validate